### ISSUE TITLE
Add support for links from https://github.com/pulls

### ISSUE THREAD

**Issue by BenJKuhn** [henrik-me/Github-Codeflow-Extension-Edge#2]
The top-level menu pull requests link is not yet supported.

**Comment by henrik-me** [comment]
@BenJKuhn : Not sure what you mean. As far as I can see the pull request list shows the data nicely.

**Comment by BenJKuhn** [comment]
I'll check again, but I haven't seen the list show up on that page successfully yet. It could be related to the loading issue I was seeing, but I haven't worked through it. Pull requests from an individual project work fine. It's only the "Pull requests" link at the very top of the page that I'm referring to here, which shows all of your own pull requests.

**Comment by henrik-me** [comment]
great. I saw it working .. but right now it only works on some lists for me.

**Comment by henrik-me** [comment]
done
