### ISSUE TITLE
Unable to use drop down in Discussion comments

### ISSUE THREAD

**Issue by jennyf19** [henrik-me/Github-Codeflow-Extension-Edge#3]
Using 2.19.1111.3 (not sure if this is the latest version or not), but when there is a Discussion comment, and I need to use one of the drop down options:
![image](https://user-images.githubusercontent.com/19942418/70584370-bb8e2500-1b75-11ea-9c84-dfcc115b4978.png)
I get this error message:
![image](https://user-images.githubusercontent.com/19942418/70584295-8aadf000-1b75-11ea-9351-cc92cdf56e9d.png)
and it doesn't update on GitHub. However, I can add a comment as a response and resolve the discussion that way without any issues.

**Comment by henrik-me** [comment]
Closing a very old issue. Fix is getting the latest codeflow.
